[package]
name = "daylog-email"
version = "0.2.0"
authors = ["Bill Fraser <wfraser@codewise.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
chrono = "0.4.9"
chrono-tz = "0.5.1"
failure = "0.1.5"
hostname = "0.3"
log = "0.4.8"
maildir = "0.4"
mailparse = "0.10"
nix = "0.17"
regex = "1.3.1"
ring = "0.16.9"
rusqlite = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_rusqlite = "0.23"
serde_yaml = "0.8.11"
signal-hook = "0.1.10"
stderrlog = "0.4.1"
structopt = "0.3.2"
